name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    strategy:
      matrix:
        run-config:
          - { scheme: 'netlaband', destination: 'platform=macOS'}
          # - { scheme: 'NetNewsWire-iOS', destination: 'platform=iOS Simulator,OS=13.0,name=iPhone 11' }

    steps:
    - name: Checkout Project
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Show the currently detailed version of Xcode for CLI
      run: xcode-select -p

    - name: Show what's in Applications
      run: ls -al /Applications

    - name: Switch to Xcode 11
      run: sudo xcode-select -s /Applications/Xcode_11.3.1.app

    - name: Show Build Version
      run: xcodebuild -version

    - name: Show Build Settings
      run: xcodebuild -showBuildSettings

    - name: Show Build SDK
      run: xcodebuild -showsdks

    - name: Show Available Destinations
      env:
        scheme: ${{ matrix.run-config['scheme'] }}
      run: xcodebuild -scheme ${scheme} -showdestinations

    - name: Homebrew build helpers install
      run: |
        brew install swiftlint
        brew install swiftformat

    - name: build and test
      run: xcodebuild clean test -scheme netlaband
